### ISSUE TITLE
Queue not happy at 65535

### ISSUE THREAD

**Issue by floyd-fuh** [kcwu/afl-kit#10]
So I've come back to some fuzzing and wanted to use afl-cmin.py again. At first it looked like everything worked fine, but then suddenly afl-cmin.py stopped and no more traces were being obtained.

First of all, I have a very large corpus I'd like to cmin. It's 80771 files. As I wanted to know where it stops, I added a couple of logger.debug statements like this:

```
[...]
    logger.info('Obtaining trace results')
    logger.debug('of '+str(len(files))+" files")
    num = 0
    for job in enumerate(files):
        print str(num)+'\r',
        sys.stdout.flush()
        job_queue.put(job)
        num += 1
    logger.debug('Done putting jobs into queue')
[...]
```

What it does is simply print the number of files that were put into job_queue.put(). When I ran this again, the tool stopped *exactly* when 65535 files were processed and we are all familiar with that number (2 to the power of 16 minus 1) and then I pressed Ctrl+C when it was stuck:

```
$ /opt/afl-kit/afl-cmin.py --debug -m 1000 -w 1 -C -i corpus_clean_flat/ -o crashes/ ../../fuzzerside/interface @@
2018-02-18 13:00:58,041 - INFO - Found 80771 input files in 1 directories
2018-02-18 13:01:00,000 - INFO - Remain 80771 files after dedup
2018-02-18 13:01:00,000 - INFO - Testing the target binary
2018-02-18 13:01:00,000 - DEBUG - run command line: /opt/afl-2.52b/afl-showmap -m 1000 -t none -o - -Z -- ../../fuzzerside/interface corpus_clean_flat/n_structure_no_data.json
2018-02-18 13:01:00,101 - INFO - ok, 1593 tuples recorded
2018-02-18 13:01:00,102 - INFO - Obtaining trace results
2018-02-18 13:01:00,103 - DEBUG - of 80771 files
65535
^CTraceback (most recent call last):
  File "/opt/afl-kit/afl-cmin.py", line 323, in <module>
    main()
  File "/opt/afl-kit/afl-cmin.py", line 261, in main
    job_queue.put(job)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/queues.py", line 101, in put
Process PoolWorker-1:
Traceback (most recent call last):
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    if not self._sem.acquire(block, timeout):
KeyboardInterrupt
    self.run()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/pool.py", line 102, in worker
    task = get()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/queues.py", line 378, in get
    return recv()
KeyboardInterrupt
^CError in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/util.py", line 325, in _exit_function
    p.join()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/process.py", line 145, in join
    res = self._popen.wait(timeout)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/forking.py", line 154, in wait
    return self.poll(0)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/forking.py", line 135, in poll
    pid, sts = os.waitpid(self.pid, flag)
KeyboardInterrupt
Error in sys.exitfunc:
Traceback (most recent call last):
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/util.py", line 325, in _exit_function
    p.join()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/process.py", line 145, in join
    res = self._popen.wait(timeout)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/forking.py", line 154, in wait
    return self.poll(0)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/forking.py", line 135, in poll
    pid, sts = os.waitpid(self.pid, flag)
KeyboardInterrupt
```

Did you ever test afl-cmin.py with more than 65'535 files?

I'm currently porting the script from python 2 to python 3 to see if the problem will still exist, but I'm unsure if that's going to solve the problem at all and if I'm really going to finish the port.

**Comment by kcwu** [comment]
Yes, I have ever tested with more than 64k. For example, the performance numbers in readme file was obtained with 79k files.

From `/usr/local/lib/python2.7/multiprocessing/queues.py`,

I found these lines
```
class Queue(object):
    def __init__(self, maxsize=0):
        if maxsize <= 0:
            maxsize = _multiprocessing.SemLock.SEM_VALUE_MAX
```
I guess its value is 65535 or 65536 on your system. Could you check its value?

However, even with small maxsize, afl-cmin.py should still work. When the queue is full, the `put` will block a while. But it should continue after workers consumed the queue. Does your program hang forever, or just pause a while?

**Comment by floyd-fuh** [comment]
Ok. Then that might really be system dependent, I’m on OSX.

SEM_VALUE_MAX is 32767, so basically the number jumps up to 32767 in 1 second, then it slowly counts up (so the put does block really shortly) and then comes to a full halt at 65535.

**Comment by kcwu** [comment]
Oh, I know what happened. At first, `job_queue` was full, so it paused at 32767. It can go up because the workers started to consume `job_queue`. It stopped again because the workers filled up `progress_queue` and all workers stuck.

Could you try following fix?
```
job_queue = multiprocessing.Queue(len(files) + len(args.workers))
```

**Comment by floyd-fuh** [comment]
As args.workers is already an int I get:
`TypeError: object of type 'int' has no len()`
Then I tried:
`job_queue = multiprocessing.Queue(len(files) + args.workers)`
Which gets me:
```
Traceback (most recent call last):
  File "/opt/afl-kit/afl-cmin.py", line 323, in <module>
    main()
  File "/opt/afl-kit/afl-cmin.py", line 245, in main
    job_queue = multiprocessing.Queue(len(files)+args.workers)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/__init__.py", line 218, in Queue
    return Queue(maxsize)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/queues.py", line 69, in __init__
    self._sem = BoundedSemaphore(maxsize)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/synchronize.py", line 130, in __init__
    SemLock.__init__(self, SEMAPHORE, value, value)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/synchronize.py", line 75, in __init__
    sl = self._semlock = _multiprocessing.SemLock(kind, value, maxvalue)
OSError: [Errno 22] Invalid argument
```
As I use -w 1 the number passed to the constructor is 80772.

**Comment by floyd-fuh** [comment]
I think this is my problem:
https://stackoverflow.com/questions/5900985/multiprocessing-queue-maxsize-limit-is-32767
and I'm not planning on implementing this:
http://peter-hoffmann.com/2012/python-simple-queue-redis-queue.html

Especially as I only run -w 1, simply removing the multiprocessing entirely seems reasonable.

However, in the meantime stock afl-cmin did it's job already, so I'll probably be too lazy for any of this...

**Comment by kcwu** [comment]
I found a workaround. Because `progress_queue` is only showing progress and useless, you can comment it out.

That is, remove line 201-203
```
                self.p_out.put(idx)
            else:
                self.p_out.put(None)
```
and line 269-272
```
    for _ in tqdm(files):
        idx = progress_queue.get()
        if idx is not None:
            effective += 1
```

**Comment by kcwu** [comment]
Because `progress_queue` is just for progress reporting and useless. You can try following workaround:

1. Remove line 201-203
```
                self.p_out.put(idx)
            else:
                self.p_out.put(None)
```
2. Remove line 269-272
```
    for _ in tqdm(files):
        idx = progress_queue.get()
        if idx is not None:
            effective += 1
```

**Comment by kcwu** [comment]
Better fix should run line 261-266 on a separate thread. But I don't have time to fix it, patch welcome.
